code --install-extension SirTori.indenticator
code --install-extension abusaidm.html-snippets
code --install-extension angryobject.react-pure-to-class-vscode
code --install-extension Angular.ng-template
code --install-extension blanu.vscode-styled-jsx
code --install-extension burkeholland.simple-react-snippets
code --install-extension capaj.vscode-exports-autocomplete
code --install-extension christian-kohler.npm-intellisense
code --install-extension codezombiech.gitignore
code --install-extension cssho.vscode-svgviewer
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension gottfired.css2react
code --install-extension magicstack.MagicPython
code --install-extension mechatroner.rainbow-csv
code --install-extension Mikael.Angular-BeastCode
code --install-extension mikestead.dotenv
code --install-extension ms-python.python
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension PeterJausovec.vscode-docker
code --install-extension ricard.postcss
code --install-extension richie5um2.snake-trail
code --install-extension robertohuertasm.vscode-icons
code --install-extension sdras.night-owl
code --install-extension shardulm94.trailing-spaces
code --install-extension silvenon.mdx
code --install-extension wix.vscode-import-cost